[workspace]
name = "bdcc-project2"
version = "0.1.0"
description = "Environment for BDCC Project 2 pipelines and benchmarks"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.14.*"
pip = "*"
setuptools = "<81"
openjdk = "==17.0.10"
cmake = "*"
pyspark = "*"
dask = "*"
distributed = "*"
joblib = "*"
scikit-learn = "*"
xgboost = "*"
dask-ml = "*"
requests = "*"
pydantic = "*"
matplotlib = "*"
jupyter = "*"
notebook = "*"
ipykernel = "*"
google-cloud-storage = "*"
gcsfs = "*"
